INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (1,'Água de coco verde ',62,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (2,'Café com açúcar ',33,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (3,'Café sem açúcar ',3,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (4,'Caldo de cana ',202,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (5,'Suco de abacaxi natural ',100,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (6,'Suco de acerola natural ',36,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (7,'Suco de maçã natural ',154,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (8,'Suco de manga natural ',109,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (9,'Suco de melão natural ',60,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (10,'Suco de milho verde natural ',271,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (11,'Suco de morango natural ',39,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (12,'Suco de pêssego natural ',77,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (13,'Suco de tomate fresco ',27,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (14,'Aguardente ',554,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (15,'Cerveja  ',147,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (16,'Cerveja light ',148,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (17,'Champanhe  ',85,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (18,'Chope ',180,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (19,'Uísque  ',240,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (20,'Vinho branco doce ',178,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (21,'Vinho branco seco ',107,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (22,'Vinho Rosé ',93,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (23,'Vinho tinto seco ',107,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (24,'Vodka  ',48,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (25,'Coca-Cola ',137,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (26,'Coca-Cola Light ',2,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (27,'Fanta  ',189,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (28,'Fanta Diet ',15,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (29,'Gatorate - todos os sabores ',109,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (30,'Guaraná ',75,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (31,'Guaraná diet ',4,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (32,'Sport Drink limão ',51,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (33,'Sprite ',115,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (34,'Sprite diet limão ',5,'copo');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (35,'Alcatra assada ',301,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (36,'Alcatra frita ',235,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (37,'Almôndega caseira de carne ',61,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (38,'Almôndega de frango ',54,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (39,'Almôndega de peru ',46,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (40,'Antecoxa de frango assada ',109,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (41,'Baby beef ',120,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (42,'Bacon fatiado ',54,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (43,'Bacon frito ',198,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (44,'Bisteca de porco ',337,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (45,'Costeleta de porco ',483,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (46,'Coxa de frango ',144,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (47,'Coxa de frango assada c/pele ',110,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (48,'Coxa de frango assada s/pele ',98,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (49,'Coxa de frango cozida ',120,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (50,'Cupim ',375,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (51,'Fígado de boi frito ',210,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (52,'Fígado de galinha ',35,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (53,'Filé de frango ',101,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (54,'Filé mignon ',140,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (55,'Hamburger bovina ',116,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (56,'Hamburger calabresa ',149,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (57,'Hamburger de chester ',105,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (58,'Hamburger de frango ',179,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (59,'Lagarto de boi assado ',170,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (60,'Leitão ',308,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (61,'Língua de boi cozida ',287,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (62,'Lombo assado ',272,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (63,'Maminha ',141,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (64,'Miolo de coxão mole ',120,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (65,'Moela de galinha ',78,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (66,'Músculo cozido ',180,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (67,'Patinho de boi assado ',200,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (68,'Peito de frango s/pele ',100,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (69,'Pernil de porco assado ',196,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (70,'Perú ',155,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (71,'Picanha ',287,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (72,'Rã ',128,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (73,'Rabo de porco salgado ',426,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (74,'Rosbife ',83,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (75,'Tender ',210,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (76,'Apresuntado ',22,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (77,'Blanquet de peru ',13,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (78,'Copa fatiada maturada ',22,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (79,'Lingüiça calabresa ',300,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (80,'Lingüiça de frango ',166,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (81,'Lingüiça de peru defumada ',148,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (82,'Lingüiça toscana ',255,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (83,'Lombo canadense ',21,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (84,'Lombo defumado ',29,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (85,'Morcela ',258,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (86,'Mortadela ',41,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (87,'Mortadela de frango ',20,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (88,'Paio ',314,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (89,'Peito de peru defumado ',14,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (90,'Presunto cozido ',18,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (91,'Presunto cru ',54,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (92,'Salame italiano ',10,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (93,'Salaminho ',10,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (94,'Salsinha ',120,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (95,'Salsicha light de chester ',64,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (96,'Salsicha Hot Dog ',115,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (97,'Salsichão ',30,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (98,'Anchova cozida ',118,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (99,'Anchova à milanesa ',210,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (100,'Atum cru ',146,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (101,'Bacalhau cozido ',100,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (102,'Cação cozido ',129,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (103,'Camarão cozido ',82,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (104,'Camarão frito ',310,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (105,'Casquinha de Caranguejo ',250,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (106,'Casquinha de Siri ',413,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (107,'Caviar ',24,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (108,'Dourado ',88,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (109,'Haddock cozido ',100,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (110,'Kani-Kama ',13,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (111,'Lagosta cozida s/ molho ',196,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (112,'Linguado assado ou grelhado ',90,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (113,'Lula cozida ',93,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (114,'Lula frita empanada ',373,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (115,'Mariscos cozidos ',96,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (116,'Mexilhão cozido ',79,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (117,'Namorado cozido ',122,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (118,'Ostras ',81,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (119,'Ovas de peixe cruas ',125,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (120,'Pescada cozida ',97,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (121,'Pintado grelhado ',208,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (122,'Polvo cru ',64,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (123,'Robalo ',72,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (124,'Salmão assado ou grelhado ',292,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (125,'Salmão cru ',211,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (126,'Sardinha grelhada ',97,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (127,'Sardinha em óleo comestível ',174,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (128,'Sardinha em conserva com azeite ',298,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (129,'Tainha Cozida ',204,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (130,'Truta assada ou grelhada ',378,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (131,'Água e sal ',32,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (132,'Biscoito de manteiga ',500,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (133,'Biscoito integral de trigo ',28,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (134,'Champanhe ',40,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (135,'Cream Cracker ',31,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (136,'Leite ',24,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (137,'Maisena ',20,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (138,'Maria ',25,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (139,'Palitinhos salgados ',383,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (140,'Passatempo alpino ',76,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (141,'Recheado chocolate ',72,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (142,'Recheado morango ',73,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (143,'Salclic aperitivo ',11,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (144,'Waffer chocolate ',41,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (145,'Caramelo ao leite ',21,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (146,'Goma média ',18,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (147,'Halls ',19,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (148,'Halls diet ',8,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (149,'Jujuba ',5,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (150,'Ana Maria Pullman ',130,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (151,'Bolo de cenoura caseiro ',135,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (152,'Bolo de cenoura com cobertura de chocolate ',371,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (153,'Bolo de chocolate ',171,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (154,'Bolo de fubá caseiro ',310,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (155,'Bolo de Laranja ',173,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (156,'Bolo pão-de-ló ',268,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (157,'Bolo de coco ',186,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (158,'Aerado ao leite ',167,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (159,'Alfajor chocolate ',190,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (160,'Alpino Bombom chocolate ao leite ',71,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (161,'Chocolate meio-amargo ',1074,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (162,'Ao leite ',1044,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (163,'Baton ',66,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (164,'Bis ',39,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (165,'Chocolate em pó solúvel ',22,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (166,'Diamante Negro ',156,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (167,'Diplomata ',60,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (168,'Chocolate Branco ',170,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (169,'Ouro Branco ',114,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (170,'Sulflair ',271,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (171,'Trufas ',89,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (172,'Amendoim c/ chocolate ',140,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (173,'Apfelstrudell ',296,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (174,'Arroz-doce ',164,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (175,'Baba-de-moça ',615,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (176,'Banana Caramelada ',140,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (177,'Bananada ',254,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (178,'Banana passa ',28,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (179,'Bomba de chocolate ',187,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (180,'Bomba de chocolate c/ cobertura de chocolate ',296,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (181,'Bombocado ',91,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (182,'Brigadeiro ',96,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (183,'Cajuzinho ',102,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (184,'Calda de caramelo ',55,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (185,'Calda de chocolate com leite ',109,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (186,'Canjica ',226,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (187,'Chantibon ',67,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (188,'Claybon Amendocrem ',123,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (189,'Cobertura de caramelo ',156,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (190,'Cobertura de cereja ',147,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (191,'Cobertura de chocolate ',128,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (192,'Cobertura de marshmellow ',50,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (193,'Cocada Branca ',55,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (194,'Creme de amendoim ',88,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (195,'Creme de marshmellow ',158,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (196,'Doce de Banana mole ',46,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (197,'Doce de leite ',158,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (198,'Folheado com creme ',704,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (199,'Framboesa em calda ',29,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (200,'Geléia de goiaba ',30,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (201,'Geléia de morango ',39,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (202,'Geléia de mocotó ',36,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (203,'Marmelada ',264,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (204,'Marrom glacê ',270,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (205,'Mel com própolis ',65,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (206,'Mel de abelhas ',62,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (207,'Mousse de chocolate ',333,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (208,'Paçoca ',114,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (209,'Pamonha ',135,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (210,'Papo-de-anjo ',150,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (211,'Pastel de Santa Clara ',143,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (212,'Pavê ',200,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (213,'Pé-de-moleque ',46,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (214,'Pêssego em calda ',81,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (215,'Pudim de arroz caseiro ',230,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (216,'Quindim caseiro ',314,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (217,'Rabanada ',445,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (218,'Rapadura ',84,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (219,'Sonho ',573,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (220,'Suspiro pequeno ',37,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (221,'Abacaxi ',68,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (222,'Cereja ',68,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (223,'Framboesa ',68,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (224,'Limão ',68,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (225,'Morango ',68,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (226,'Uva ',68,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (227,'Ao leite coco ',94,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (228,'Ao leite morango ',123,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (229,'Banana Split ',843,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (230,'Colegial ',482,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (231,'Milk-Shake Baunilha ',336,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (232,'Milk-Shake Chocolate ',380,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (233,'Sorvete de massa chocolate creme morango e coco ',75,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (234,'Sorvete de massa de limão ',62,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (235,'Sundae ',616,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (236,'Açúcar branco refinado ',40,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (237,'Açúcar Mascavo ',36,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (238,'Alcaparra sem azeitona ',2,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (239,'Alho ',7,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (240,'Caldo de carne ',33,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (241,'Caldo de galinha ',35,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (242,'Cebola crua ',6,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (243,'Cheiro verde ',4,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (244,'Curry ',23,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (245,'Erva-doce ',1,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (246,'Extrato de tomate ',14,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (247,'Ketchup ',20,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (248,'Leite de coco ',132,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (249,'Molho de pimenta vermelha ',2,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (250,'Molho Inglês ',5,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (251,'Mostarda ',8,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (252,'Páprica ',20,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (253,'Pimenta-do-reino ',1,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (254,'Sal branco refinado ',0,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (255,'Shoyu ',6,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (256,'Vinagre ',3,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (257,'Branco ',28,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (258,'Chutney de manga ',82,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (259,'Maionese ',141,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (260,'Molho agridoce ',31,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (261,'Molho de iogurte ',21,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (262,'Molho roquefort ',78,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (263,'Molho rose ',135,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (264,'Molho de tomate caseiro ',10,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (265,'Molho tártaro ',64,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (266,'Azeite-de-dendê ',89,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (267,'Azeite de oliva ',90,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (268,'Banha de galinha ',126,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (269,'Banha de porco industrializada ',180,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (270,'Gordura vegetal hidrogenada ',180,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (271,'Manteiga com sal ',77,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (272,'Margarina ',74,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (273,'Óleo de algodão ',90,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (274,'Óleo de amendoim ',90,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (275,'Óleo de canola ',90,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (276,'Óleo de fígado de bacalhau ',130,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (277,'Óleo de gergelim ',90,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (278,'Óleo de girassol ',90,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (279,'Óleo de milho ',90,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (280,'Óleo de peixe ',90,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (281,'Óleo de soja ',90,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (282,'Abacate ',177,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (283,'Abacaxi ',50,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (284,'Acerola ',4,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (285,'Banana-da-terra ',117,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (286,'Banana-maçã ',72,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (287,'Banana-nanica ',87,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (288,'Banana-prata crua ',55,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (289,'Caju ',37,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (290,'Cana-de-açúcar ',64,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (291,'Caqui chocolate ',74,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (292,'Castanha de caju picada ',835,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (293,'Cereja ',97,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (294,'Coco ralado fresco ',50,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (295,'Figo maduro ',68,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (296,'Framboesa ',12,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (297,'Goiaba vermelha ',43,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (298,'Graviola ',60,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (299,'Guaraná ',69,'grama');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (300,'Kiwi ',46,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (301,'Laranja ',46,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (302,'Limão ',12,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (303,'Maçã verde ',79,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (304,'Maçã vermelha ',85,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (305,'Mamão maduro ',36,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (306,'Manga ',230,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (307,'Maracujá comum (polpa) ',28,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (308,'Melancia ',24,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (309,'Melão ',19,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (310,'Morango ',43,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (311,'Nozes ',71,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (312,'Pêra crua ',68,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (313,'Pêra seca ',144,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (314,'Pêssego ',63,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (315,'Tangerina ',50,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (316,'Uva branca nacional ',130,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (317,'Uva passa ',54,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (318,'Agite morango Danone ',90,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (319,'Coalhada ',52,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (320,'Batavo c/ mel ',210,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (321,'Corpus Diet morango ',74,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (322,'Danette ',75,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (323,'Danoninho morango ',71,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (324,'Danup ',170,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (325,'Iogurte batido com açúcar e mel ',180,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (326,'Iogurte desnatado light Batavo ',88,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (327,'Iogurte natural batido Vigor ',176,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (328,'Iogurte natural batido light Vigor ',78,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (329,'Iogurte natural Paulista ',89,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (330,'Iogurte natural light Paulista ',57,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (331,'Neston c/ cereal e frutas ',202,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (332,'Parmalat natural desnatado ',88,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (333,'Shake morango Nestlé ',376,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (334,'Achocolatado Leco ',194,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (335,'Chocolate pronto Glória ',204,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (336,'Creme de leite ',37,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (337,'Leite com chocolate ',222,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (338,'Leite condensado ',65,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (339,'Leite de búfala ',253,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (340,'Leite de cabra ',220,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (341,'Leite de soja ',120,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (342,'Leite em pó desnatado ',73,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (343,'Leite em pó integral ',99,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (344,'Leite integral ',150,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (345,'Leite longa vida c/ ferro ',146,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (346,'Leite semidesnatado ',115,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (347,'Brie ',110,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (348,'Camembert ',136,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (349,'Catupiry ',49,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (350,'Cheddar americano ',107,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (351,'Cottage Lacreme ',55,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (352,'Cream cheese light Danúbio ',38,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (353,'Cream cheese tradicional Alouette ',70,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (354,'Edam ',92,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (355,'Ementhal ',85,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (356,'Estepe ',52,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (357,'Gorgonzola ',119,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (358,'Gouda Luna ',107,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (359,'Gruyère francês ',93,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (360,'Mussarela ',47,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (361,'Palmira ',114,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (362,'Parmesão ',121,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (363,'Pecorino ',128,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (364,'Petit-Suisse ',45,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (365,'Polenguinho ',57,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (366,'Prato ',53,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (367,'Provolone ',51,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (368,'Queijo-de-minas ',112,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (369,'Queijo-de-minas semicurado ',90,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (370,'Queijo-do-reino ',155,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (371,'Ricota de leite integral ',54,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (372,'Requeijão cremoso Nestlé ',54,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (373,'Requeijão cremoso light Nestlé ',36,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (374,'Roquefort ',100,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (375,'Suíço ',121,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (376,'Tofú (queijo de soja) ',68,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (377,'Omelete ',170,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (378,'Ovo de codorna ',33,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (379,'Ovo de galinha cozido ',78,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (380,'Ovo de galinha frito ',108,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (381,'Ovo mexido ',195,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (382,'Abóbora ',40,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (383,'Agrião ',28,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (384,'Aipim frito ',353,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (385,'Alface ',4,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (386,'Amendoim ',549,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (387,'Arroz branco cozido ',41,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (388,'Arroz integral cozido ',22,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (389,'Aspargo cozido ',4,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (390,'Azeitona preta ',4,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (391,'Azeitona verde ',5,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (392,'Batata-doce assada ',143,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (393,'Batata-doce frita ',383,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (394,'Batata palha frita ',220,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (395,'Berinjela ',489,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (396,'Beterraba ',55,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (397,'Brócolis ',23,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (398,'Cebola ',32,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (399,'Cebola cozida ',54,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (400,'Cenoura ',45,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (401,'Cenoura cozida ',54,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (402,'Couve-flor cozida ',41,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (403,'Ervilha em conserva ',19,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (404,'Escarola ',7,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (405,'Espinafre ',38,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (406,'Feijão-branco cozido ',24,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (407,'Feijão cozido e desidratado ',78,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (408,'Feijão-preto cozido ',14,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (409,'Mandioca frita ',352,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (410,'Palmito cru ',26,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (411,'Palmito em conserva ',22,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (412,'Pepino cru com casca ',21,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (413,'Pepino cru sem casca ',5,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (414,'Repolho ',33,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (415,'Repolho cozido ',13,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (416,'Tomate cozido ',18,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (417,'Tomate maduro ',20,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (418,'Vagem cozida ',52,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (419,'Baguete ',70,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (420,'Baguete com gergelim ',82,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (421,'Bisnaguinha ',45,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (422,'Brioche ',210,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (423,'Broa de milho ',150,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (424,'Croissant ',247,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (425,'Panetone ',283,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (426,'Pão de batata-inglesa ',90,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (427,'Pão de cará ',140,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (428,'Pão de centeio integral ',58,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (429,'Pão francês ',135,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (430,'Pão de fôrma tradicional ',74,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (431,'Pão de hambúrguer ',278,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (432,'Pão de hot-dog ',286,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (433,'Pão de mel c/ cobertura de chocolate ',91,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (434,'Pão de queijo ',68,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (435,'Pão integral de trigo ',261,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (436,'Pão sírio integral ',147,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (437,'Canelone de presunto e queijo à bolonhesa ',552,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (438,'Capelete de carne ',278,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (439,'Capelete de frango ',279,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (440,'Espaguete comum cozido ',233,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (441,'Espaguete ao sugo ',163,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (442,'Lasanha ',139,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (443,'Macarrão à carbonara ',362,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (444,'Macarrão integral cozido ',195,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (445,'Macarrão com molho de tomate e queijo ',104,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (446,'Macarrão cozido ',154,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (447,'Macarronada ',289,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (448,'Nhoque s/ molho ',227,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (449,'Pizza alho e óleo ',276,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (450,'Pizza de calabresa ',412,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (451,'Pizza de catupiry com tomate ',324,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (452,'Pizza de champignon c/ mussarela ',249,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (453,'Pizza de escarola c/ mussarela ',246,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (454,'Pizza de frango com catupiry ',305,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (455,'Pizza de mussarela ',304,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (456,'Pizza margherita ',275,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (457,'Pizza portuguesa ',396,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (458,'Pizza quatro queijos ',432,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (459,'Aveia em flocos ',50,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (460,'Corn Flakes ',217,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (461,'Farinha de amendoim ',56,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (462,'Farinha de arroz ',53,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (463,'Farinha de aveia-crua ',57,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (464,'Farinha de batata-doce ',52,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (465,'Farinha de batata-inglesa ',53,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (466,'Farinha de fubá de milho ',69,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (467,'Farinha de mandioca ',54,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (468,'Farinha de milho integral ',30,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (469,'Farinha de rosca ',54,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (470,'Farinha de trigo ',54,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (471,'Granola com castanhas ',300,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (472,'Grão de aveia cru ',48,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (473,'Germe de trigo ',55,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (474,'Maisena ',52,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (475,'Malte em pó ',56,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (476,'Arroz com feijão ',75,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (477,'Arroz-de-carreteiro ',56,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (478,'Bife à parmegiana ',485,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (479,'Carne de panela ',230,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (480,'Creme de milho c/ leite e maisena ',72,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (481,'Empadão de frango ',359,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (482,'Estrogonofe ',332,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (483,'Farofa ',169,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (484,'Feijoada ',273,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (485,'Frango xadrez ',180,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (486,'Leitão a pururuca ',966,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (487,'Moqueca de peixe ',325,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (488,'Panqueca ',60,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (489,'Pimentão assado com carne ',298,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (490,'Rabada ',389,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (491,'Ratatoille ',38,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (492,'Risoto caseiro ',52,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (493,'Salada de batata ',147,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (494,'Sashimi c/ atum namorado, linguado e nabo ',363,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (495,'Tabule ',52,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (496,'Torta de camarão ',310,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (497,'Vatapá ',227,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (498,'Beirute ',510,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (499,'Cachorro-quente com maionese e molho vinagrete ',624,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (500,'Cachorro-quente com ketchup ',314,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (501,'Cachorro-quente com mostarda ',330,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (502,'Cachorro-quente com ketchup e mostarda ',342,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (503,'Cheeseburguer ',305,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (504,'Cheese salada com maionese ',738,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (505,'Hambúrguer ',296,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (506,'Misto quente ',283,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (507,'Sanduíche de lingüiça ',370,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (508,'Sanduíche de peito de peru ',220,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (509,'Sanduíche de queijo quente ',340,'unidade');
INSERT INTO `alimento`(idalimento, descricao, cal, unidade) VALUES (510,'Sanduíche de salada de atum ',417,'unidade');

INSERT INTO `horrariorefeicao` VALUES (1,'Café da Manhã'),(2,'Lanche da Manhã'),(3,'Almoço'),(4,'Lanche da Tarde'),(5,'Jantar'),(6,'Lanche da Noite');
